import { NextResponse } from 'next/server';
import sql from '@/lib/db';

/**
 * POST /api/admin/blog/cleanup (requires CRON_SECRET as query param or header)
 * 
 * Removes posts generated by the deleted blog-generate shortcut route.
 * These posts have: no interview_id, no quality score entry, and content
 * sourced from founder-answers.json instead of the proper pipeline.
 */
export async function POST(request: Request) {
  const { searchParams } = new URL(request.url);
  const secret = searchParams.get('secret') || request.headers.get('X-Cron-Secret') || '';
  if (secret !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    // Find orphan posts: no interview_id, no quality score, status = draft/scheduled
    const orphans = await sql`
      SELECT bp.id, bp.title, bp.status, bp.created_at
      FROM blog_posts bp
      LEFT JOIN blog_quality_scores bqs ON bqs.blog_post_id = bp.id
      WHERE bp.interview_id IS NULL
        AND bqs.blog_post_id IS NULL
        AND bp.status IN ('draft', 'scheduled')
      ORDER BY bp.created_at DESC
    `;

    if (orphans.length === 0) {
      return NextResponse.json({ deleted: 0, message: 'No orphan posts found' });
    }

    // Delete associated records first (images, quality scores, syndication logs)
    for (const post of orphans) {
      await sql`DELETE FROM blog_images WHERE blog_post_id = ${post.id}`;
      await sql`DELETE FROM blog_syndication_log WHERE blog_post_id = ${post.id}`;
      await sql`DELETE FROM blog_syndication_queue WHERE blog_post_id = ${post.id}`;
      await sql`DELETE FROM used_questions WHERE blog_post_id = ${post.id}`;
    }

    // Delete the posts
    const ids = orphans.map((p: any) => p.id);
    await sql`DELETE FROM blog_posts WHERE id = ANY(${ids}::uuid[])`;

    return NextResponse.json({
      deleted: orphans.length,
      posts: orphans.map((p: any) => ({ id: p.id, title: p.title, status: p.status })),
      message: 'Shortcut posts removed',
    });
  } catch (e: any) {
    return NextResponse.json({ error: e.message }, { status: 500 });
  }
}
